
package presentacion;

import dato.Conexion;
import dato.PersonaDAO;
import domain.Persona;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.basic.BasicLookAndFeel;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.multi.MultiLookAndFeel;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.swing.plaf.synth.SynthLookAndFeel;

/**
 *
 * @author 50765
 */
public class FrmRegistro extends javax.swing.JFrame {
    
   
    public FrmRegistro() {
        initComponents();  
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_bd = new javax.swing.ButtonGroup();
        panel_registro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfld_lastname = new javax.swing.JTextField();
        txfld_age = new javax.swing.JTextField();
        txfld_name = new javax.swing.JTextField();
        txfld_id = new javax.swing.JTextField();
        txfld_gmail = new javax.swing.JTextField();
        btn_enviarDatos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        RAD_INSERT = new javax.swing.JRadioButton();
        RAD_DELETE = new javax.swing.JRadioButton();
        RAD_UPDATE = new javax.swing.JRadioButton();
        RAD_SELECT = new javax.swing.JRadioButton();
        btn_config = new javax.swing.JButton();
        menu_var = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Registro BD");

        panel_registro.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Persona"));
        panel_registro.setToolTipText("Llene los campos");
        panel_registro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel2.setText("Lastname");

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel3.setText("Age");

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel4.setText("Gmail");

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel5.setText("ID");

        txfld_lastname.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        txfld_lastname.setForeground(new java.awt.Color(51, 51, 51));
        txfld_lastname.setEnabled(false);

        txfld_age.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        txfld_age.setForeground(new java.awt.Color(51, 51, 51));
        txfld_age.setEnabled(false);

        txfld_name.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        txfld_name.setForeground(new java.awt.Color(51, 51, 51));
        txfld_name.setEnabled(false);

        txfld_id.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        txfld_id.setForeground(new java.awt.Color(51, 51, 51));
        txfld_id.setEnabled(false);

        txfld_gmail.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        txfld_gmail.setForeground(new java.awt.Color(51, 51, 51));
        txfld_gmail.setEnabled(false);

        btn_enviarDatos.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btn_enviarDatos.setForeground(new java.awt.Color(51, 51, 51));
        btn_enviarDatos.setText("Send Data");
        btn_enviarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_registroLayout = new javax.swing.GroupLayout(panel_registro);
        panel_registro.setLayout(panel_registroLayout);
        panel_registroLayout.setHorizontalGroup(
            panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txfld_name, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txfld_age, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfld_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_registroLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfld_id, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_registroLayout.createSequentialGroup()
                        .addComponent(btn_enviarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(panel_registroLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfld_gmail, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_registroLayout.setVerticalGroup(
            panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_registroLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txfld_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfld_gmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txfld_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfld_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panel_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfld_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_enviarDatos))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Accion Realizar"));
        jPanel1.setToolTipText("Seleccione una de las opciones");

        group_bd.add(RAD_INSERT);
        RAD_INSERT.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        RAD_INSERT.setForeground(new java.awt.Color(51, 51, 51));
        RAD_INSERT.setText("INSERT");

        group_bd.add(RAD_DELETE);
        RAD_DELETE.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        RAD_DELETE.setForeground(new java.awt.Color(51, 51, 51));
        RAD_DELETE.setText("DELETE");

        group_bd.add(RAD_UPDATE);
        RAD_UPDATE.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        RAD_UPDATE.setForeground(new java.awt.Color(51, 51, 51));
        RAD_UPDATE.setText("UPDATE");

        group_bd.add(RAD_SELECT);
        RAD_SELECT.setFont(new java.awt.Font("Gill Sans MT", 3, 12)); // NOI18N
        RAD_SELECT.setForeground(new java.awt.Color(51, 51, 51));
        RAD_SELECT.setText("SELECT");

        btn_config.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btn_config.setForeground(new java.awt.Color(51, 51, 51));
        btn_config.setText("Confirm");
        btn_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RAD_SELECT)
                .addGap(12, 12, 12)
                .addComponent(RAD_INSERT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RAD_UPDATE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RAD_DELETE)
                .addGap(18, 18, 18)
                .addComponent(btn_config)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RAD_INSERT)
                    .addComponent(RAD_DELETE)
                    .addComponent(RAD_UPDATE)
                    .addComponent(RAD_SELECT)
                    .addComponent(btn_config))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jMenu1.setText("Ver Registro");

        jMenuItem1.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jMenuItem1.setText("Registro Completo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menu_var.add(jMenu1);

        setJMenuBar(menu_var);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panel_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configActionPerformed
       
        if(RAD_INSERT.isSelected()){
            txfld_name.setEnabled(true);
            txfld_lastname.setEnabled(true);
            txfld_age.setEnabled(true); 
            txfld_gmail.setEnabled(true);
            txfld_id.setEnabled(false); 
            
        }
        if (RAD_DELETE.isSelected()){
            
            txfld_name.setEnabled(false);
            txfld_lastname.setEnabled(false); 
            txfld_age.setEnabled(false); 
            txfld_gmail.setEnabled(false);  
            txfld_id.setEnabled(true); 
        }
        
        if(RAD_UPDATE.isSelected()){
            txfld_name.setEnabled(true);
            txfld_lastname.setEnabled(true);
            txfld_age.setEnabled(true); 
            txfld_gmail.setEnabled(true);
            txfld_id.setEnabled(true);
        } 
        
        if(RAD_SELECT.isSelected()){
            
           
           
        }
        
        
    }//GEN-LAST:event_btn_configActionPerformed

    private void btn_enviarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarDatosActionPerformed
        
            Persona obj_person =new Persona();
            PersonaDAO obj_ins = new PersonaDAO(); 
            
            if(RAD_INSERT.isSelected()){
                if(txfld_name.getText().equals("")||
                   txfld_lastname.getText().equals("")|| 
                    txfld_age.getText().equals("")||
                        txfld_gmail.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Error Llene los campos vacio");
                }                
                else{
                    obj_person.setName(txfld_name.getText());
                    obj_person.setLastname(txfld_lastname.getText());
                    obj_person.setAge(Integer.parseInt(txfld_age.getText()));
                    obj_person.setGmail(txfld_gmail.getText());
                    obj_ins.INSERT(obj_person); 
                    JOptionPane.showMessageDialog(null, "Se ha insertado CORRECTAMENTE en el registro!");
                }
            } 
            if(RAD_UPDATE.isSelected()){
                if(txfld_name.getText().equals("")||
                   txfld_lastname.getText().equals("")|| 
                    txfld_age.getText().equals("")||
                        txfld_gmail.getText().equals("")||
                        txfld_id.getText().equals("")){
                    
                    JOptionPane.showMessageDialog(null,"Error , Llene los campos vacio");
                }
                else{
                    obj_person.setName(txfld_name.getText());
                    obj_person.setLastname(txfld_lastname.getText());
                    obj_person.setAge(Integer.parseInt(txfld_age.getText()));
                    obj_person.setGmail(txfld_gmail.getText()); 
                    obj_person.setId_person(Integer.parseInt(txfld_id.getText())); 
                    obj_ins.UPDATE(obj_person); 
                    JOptionPane.showMessageDialog(null,"Se ha realizado update CORRECTAMENTE en el resgistro!");
                }
            }
            if(RAD_DELETE.isSelected()){
                
                if(txfld_id.getText().equals("")){
                    
                   JOptionPane.showMessageDialog(null,"Error , Llene los campos Vacio");
                }
                else{
                    obj_person.setId_person(Integer.parseInt(txfld_id.getText())); 
                     obj_ins.DELETE(obj_person); 
                     JOptionPane.showMessageDialog(null,"Se ha eliminado CORRECTAMENTE en el registro");
                }
            }
            
            if(RAD_SELECT.isSelected()){
                              
                
            }
            
    }//GEN-LAST:event_btn_enviarDatosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         
        Dialog_Data ven_dialog = new Dialog_Data(this,true); 
        ven_dialog.setVisible(true); 
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public static void main(String args[]) {
       
     
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                try {
                    UIManager.setLookAndFeel(new NimbusLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) { 
                    ex.printStackTrace(System.out);
                }
                new FrmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RAD_DELETE;
    private javax.swing.JRadioButton RAD_INSERT;
    private javax.swing.JRadioButton RAD_SELECT;
    private javax.swing.JRadioButton RAD_UPDATE;
    private javax.swing.JButton btn_config;
    private javax.swing.JButton btn_enviarDatos;
    private javax.swing.ButtonGroup group_bd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menu_var;
    private javax.swing.JPanel panel_registro;
    private javax.swing.JTextField txfld_age;
    private javax.swing.JTextField txfld_gmail;
    private javax.swing.JTextField txfld_id;
    private javax.swing.JTextField txfld_lastname;
    private javax.swing.JTextField txfld_name;
    // End of variables declaration//GEN-END:variables
}
